### ISSUE TITLE
Faraday::ConnectionFailed: execution expired when run query with long time idle.

### ISSUE THREAD

**Issue by jhsbeat** [treasure-data/presto-client-ruby#10]
Hi. All. 

I'm using `presto-client-ruby` for my application to run query and get the results from the presto server. It works appropriately when I run a query right before create a new presto client. However, if I run a query using presto ruby client **with long time interval from initialization of the client**, it raises `Faraday::ConnectionFailed: execution expired` error. 

Here is my code for initializing the presto ruby client: 
```ruby
client = ::Presto::Client.new(
      server: CONFIG[:presto_server],
      catalog: CONFIG[:presto_catalog],
      schema: CONFIG[:presto_schema],
      user: CONFIG[:presto_user],
      time_zone: CONFIG[:presto_timezone] || "Asia/Seoul",  
      language: "English", 
      properties: {},                                          
      http_debug: Rails.env == "development" ? true : false,
    )
```

Did I miss something or do I need to initialize a client right before running a query?

**Comment by frsyuki** [comment]
Can you paste full stacktrace and the version of ruby and OS you used?

**Comment by jhsbeat** [comment]
Yes. The ruby version is `2.2.2` and OS is `Linux/Unix, CentOS 6 | 64-bit Amazon Machine Image (AMI)`.
Here is the full stack trace: 

```
Faraday::ConnectionFailed
/opt/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
/opt/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:879:in `open'
/opt/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
/opt/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
/opt/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:99:in `call'
/opt/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
/opt/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:878:in `connect'
/opt/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
/opt/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:852:in `start'
/opt/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1375:in `request'
/home/mywork/mywork/vendor/bundle/ruby/2.2.0/gems/rest_client-1.7.3/lib/restclient/net_http_ext.rb:51:in `request'
/home/mywork/mywork/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:82:in `perform_request'
/home/mywork/mywork/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `block in call'
/home/mywork/mywork/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
/home/mywork/mywork/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
/home/mywork/mywork/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
/home/mywork/mywork/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
/home/mywork/mywork/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:177:in `post'
/home/mywork/mywork/vendor/bundle/ruby/2.2.0/gems/presto-client-0.4.8/lib/presto/client/statement_client.rb:61:in `post_query_request!'
/home/mywork/mywork/vendor/bundle/ruby/2.2.0/gems/presto-client-0.4.8/lib/presto/client/statement_client.rb:50:in `initialize'
/home/mywork/mywork/vendor/bundle/ruby/2.2.0/gems/presto-client-0.4.8/lib/presto/client/query.rb:36:in `new'
/home/mywork/mywork/vendor/bundle/ruby/2.2.0/gems/presto-client-0.4.8/lib/presto/client/query.rb:36:in `start'
/home/mywork/mywork/vendor/bundle/ruby/2.2.0/gems/presto-client-0.4.8/lib/presto/client/client.rb:40:in `run'
/home/mywork/mywork/app/models/calculator.rb:294:in `calculate_by_presto'
```

**Comment by frsyuki** [comment]
I see. http.rb:879 is this:

```
      s = Timeout.timeout(@open_timeout, Net::OpenTimeout) {
        TCPSocket.open(conn_address, conn_port, @local_host, @local_port)
      }
```

The error means opening a socket took too long time. Socket is not reused.

Does the problem happen consistently if the time interval exceeds certain threshold? Or does it occasionally succeed even if client sleeps for very long time after initialization?
If it's not consistent, I think kernel parameters need to be reviewed both on client and servers. Some parameters are important to establish TCP connections reliably under high load environment.
This is an article about TCP kernel parameters: http://docs.fluentd.org/articles/before-install#optimize-network-kernel-parameters

**Comment by frsyuki** [comment]
Do you have metrics about number of TCP connection established on presto-coordinator server? `netstat -lant` shows it. If there're thousands connections, listen backlog could be filled up (and coordinator can't accept new sockets).

**Comment by jhsbeat** [comment]
Okay~ I'll take a look at both server side and client side again especially for kernel params. 
I'll close this issue and will reopen if I could find out a point to be fixed in client side. :)
Thank you very much for your help. :+1:
